#!/bin/bash

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

stop_and_purge_nginx(){
  if [[ dpkg -s nginx-light>/dev/null 2>&1 ]] || [[ dpkg -s nginx-common>/dev/null 2>&1 ]]
    then
      if systemctl is-active --quiet nginx
        then
          if systemctl stop nginx
            then
              if apt purge -y nginx-light nginx-common
                then
                  printf "${YELLOW}Nginx-light und/ oder nginx-common wurde deinstalliert.${NC}\n"
              else
                printf "${RED}Die Pakete nginx-light und/ oder nginx-common konnten nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
              fi
      elif ! systemctl is-active --quiet nginx
        then
          if apt purge -y nginx-light nginx-common
            then
              printf "${YELLOW}Nginx-light und/ oder nginx-common wurde deinstalliert.${NC}\n"
          else
            printf "${RED}Die Pakete nginx-light und/ oder nginx-common konnten nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
          fi
  else
    printf "${YELLOW}Nginx-light und/ oder nginx-common sind nicht vorhanden, fahre fort.${NC}\n"
  fi
}

stop_and_purge_shellinabox(){
  if dpkg -s shellinabox>/dev/null 2>&1
    then
      if systemctl is-active --quiet shellinabox
        then
          if systemctl stop shellinabox
            then
              if apt purge -y shellinabox
                then
                  printf "${YELLOW}Shellinabox wurde deinstalliert.${NC}\n"
              else
                printf "${RED}Das Paket shellinabox konnte nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
              fi
      elif ! systemctl is-active --quiet shellinabox
        then
          if apt purge -y shellinabox
            then
              printf "${YELLOW}Shellinabox wurde deinstalliert.${NC}\n"
          else
            printf "${RED}Das Paket shellinabox konnte nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
          fi
  else
    printf "${YELLOW}Shellinabox ist nicht vorhanden, fahre fort.${NC}\n"
  fi
}

remove_storj_variables(){
  if [[ -f /var/www/html/storj_variables ]]
    then
      rm /var/www/html/storj_variables
  else
    return 0;
  fi
}

main(){
  stop_and_purge_nginx && stop_and_purge_shellinabox && remove_storj_variables && exit 0
}

main