#!/bin/bash

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

update(){
  if apt update && apt upgrade -y
    then
      printf "${GREEN}Paketlisten und Pakete wurden aktualisiert!${NC}\n"
  else
    printf "${RED}Paketliste konnte nicht abgerufen und/ oder installiert werden, beende Skript!${NC}\n" && exit 1
  fi
}

purge_apache2(){
  if dpkg -s apache2>/dev/null 2>&1
    then
      printf "${YELLOW}Apache2 wurde als installiertes Paket auf dem Host erkannt, deinstalliere apache2.${NC}\n"
      if apt purge -y apache2
        then
          printf "${GREEN}Apache2 wurde erfolgreich deinstalliert!${NC}\n"
      else
        printf "${RED}Apache2 konnte nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
      fi
  fi
}

stop_and_purge_nginx(){
  if dpkg -s nginx-light >/dev/null 2>&1 || dpkg -s nginx-common >/dev/null 2>&1
    then
      if systemctl is-active --quiet nginx
        then
          if systemctl stop nginx
            then
              if apt purge -y nginx-light nginx-common
                then
                  printf "${YELLOW}Nginx-light und/ oder nginx-common wurde deinstalliert.${NC}\n"
              else
                printf "${RED}Die Pakete nginx-light und/ oder nginx-common konnten nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
              fi
          else
            printf "${RED}Nginx konnte nicht gestoppt werden, beende Skript!${NC}\n" && exit 1
        fi
      elif ! systemctl is-active --quiet nginx
        then
          if apt purge -y nginx-light nginx-common
            then
              printf "${YELLOW}Nginx-light und/ oder nginx-common wurde deinstalliert.${NC}\n"
          else
            printf "${RED}Die Pakete nginx-light und/ oder nginx-common konnten nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
          fi
      fi
  else
    printf "${YELLOW}Nginx-light und/ oder nginx-common sind nicht vorhanden, fahre fort.${NC}\n"
  fi
}

stop_and_purge_shellinabox(){
  if dpkg -s shellinabox>/dev/null 2>&1
    then
      if systemctl is-active --quiet shellinabox
        then
          if systemctl stop shellinabox
            then
              if apt purge -y shellinabox
                then
                  printf "${YELLOW}Shellinabox wurde deinstalliert.${NC}\n"
              else
                printf "${RED}Das Paket shellinabox konnte nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
              fi
          else
            printf "${RED}Shellinabox konnte nicht gestoppt werden, beende Skript!${NC}\n" && exit 1
          fi
      elif ! systemctl is-active --quiet shellinabox
        then
          if apt purge -y shellinabox
            then
              printf "${YELLOW}Shellinabox wurde deinstalliert.${NC}\n"
          else
            printf "${RED}Das Paket shellinabox konnte nicht deinstalliert werden, beende Skript!${NC}\n" && exit 1
          fi
      fi
  else
    printf "${YELLOW}Shellinabox ist nicht vorhanden, fahre fort.${NC}\n"
  fi
}

install_web_essentials(){
  if apt install -y nginx-light php-fpm shellinabox
    then
      printf "${GREEN}Die Pakete nginx-light, php-fpm und shellinabox wurden installiert!${NC}\n"
  else
    printf "${RED}Die Pakete nginx-light, php-fpm und shellinabox konnten nicht installiert werden, beende Skript!${NC}\n" && exit 1
  fi
}

check_nginx(){
  if systemctl is-active --quiet nginx
    then
      if systemctl stop nginx
        then
          printf "${GREEN}Nginx wurde korrekt installiert und wurde zeitweise zur Rekonfiguration gestoppt.${NC}\n"
      else
        printf "${RED}Nginx konnte nicht gestoppt werden, beende Skript!${NC}\n" && exit 1
      fi
  else
    printf "${RED}Nginx wurde nicht korrekt installiert, purge nginx-light und beende Skript!${NC}\n" && apt purge -y nginx-light && exit 1
  fi
}

copy_formular_to_var(){
  if cp ./web/index.php ./web/storj_variables.php ./web/finished.php /var/www/html/ && chown -R www-data:www-data /var/www/html/
    then
      > /var/www/html/finished
      printf "${GREEN}Das Webformular wurde erfolgreich nach /var/www/html kopiert${NC}\n"
  else
    printf "${RED}Das Webformular konnte nicht nach /var/www/html kopiert werden, beende Skript!${NC}\n" && exit 1
  fi
}

change_default_conf(){
  mv /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.old

  if cp ./web/new-default /etc/nginx/sites-enabled/default
    then
      printf "${GREEN}Die neue nginx-Config wurde eingefügt.${NC}\n"
      if systemctl start nginx
        then
          printf "${GREEN}Nginx konnte gestartet werden.${NC}\n"
      else
        printf "${RED}Nginx konnte nicht gestartet werden, beende Skript!${NC}\n" && exit 1
      fi
  else
    printf "${RED}Die neue nginx-Config konnte nicht eingefügt werden, beende Skript!${NC}\n" && exit 1
  fi
}

configure_shellinabox(){
  if systemctl disable shellinabox && systemctl stop shellinabox
    then
      pkill -f shellinaboxd
      printf "${GREEN}Der shellinabox-Service wurde erfolgreich vorübergehend gestoppt.${NC}\n"
      if shellinaboxd -b -p 4200 -m '*' --disable-ssl --css /etc/shellinabox/options-available/00_White\ On\ Black.css
        then
          printf "${YELLOW}Das Webformular ist jetzt unter folgender Adresse erreichbar: http://`hostname -I | awk '{ print $1 }'`:8080${NC}\n"
      else
        printf "${RED}Shellinabox konnte nicht gestartet werden, beende Skript!${NC}\n" && exit 1
      fi
  else
    printf "${RED}Shellinabox konnte nicht gestoppt werden, beende Skript!${NC}\n" && exit 1
  fi
}

main(){
  update && purge_apache2 && stop_and_purge_nginx && stop_and_purge_shellinabox && install_web_essentials && check_nginx && copy_formular_to_var && change_default_conf && configure_shellinabox
}

main